/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earth.gltf
Author: DigitalSte (https://sketchfab.com/stecgartist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-green-world-c94e277d35d6479fa77247ed4fb5b218
Title: Low Poly Green World
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.12, 0.44]} rotation={[-2.08, 0, 0]}>
        <group position={[0.02, 0.91, -0.01]}>
          <group position={[0, 0, -0.02]}>
            <mesh geometry={nodes['StageOne_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh geometry={nodes['StageOne_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
            <mesh geometry={nodes['StageOne_Material_#152_0'].geometry} material={materials.Material_152} />
            <mesh geometry={nodes['StageOne_Material_#117_0'].geometry} material={materials.Material_117} />
            <mesh geometry={nodes['StageOne_Material_#38_0'].geometry} material={materials.Material_38} />
            <mesh geometry={nodes['StageOne_Material_#39_0'].geometry} material={materials.Material_39} />
            <mesh geometry={nodes['StageOne_Material_#140_0'].geometry} material={materials.Material_140} />
            <mesh geometry={nodes['StageOne_Material_#318_0'].geometry} material={materials.Material_318} />
            <mesh geometry={nodes['StageOne_Material_#503_0'].geometry} material={materials.Material_503} />
            <mesh geometry={nodes['StageOne_Material_#502_0'].geometry} material={materials.Material_502} />
            <mesh geometry={nodes['StageOne_Material_#516_0'].geometry} material={materials.Material_516} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
