/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 world.gltf -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    Plane002_3: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    clouds: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere003_1: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane005_2: THREE.Mesh
    Plane007_1: THREE.Mesh
    Plane007_2: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane008_2: THREE.Mesh
    Plane008_3: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane009_2: THREE.Mesh
    Plane009_3: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane038: THREE.Mesh
    Plane038_1: THREE.Mesh
    Plane039: THREE.Mesh
    Plane039_1: THREE.Mesh
    Plane040: THREE.Mesh
    Plane040_1: THREE.Mesh
    Plane043: THREE.Mesh
    Plane043_1: THREE.Mesh
    Plane047: THREE.Mesh
    Plane047_1: THREE.Mesh
    Plane049: THREE.Mesh
    Plane049_1: THREE.Mesh
    Plane052: THREE.Mesh
    Plane052_1: THREE.Mesh
    Plane080: THREE.Mesh
    Plane080_1: THREE.Mesh
    Plane081: THREE.Mesh
    Plane081_1: THREE.Mesh
    Plane082: THREE.Mesh
    Plane082_1: THREE.Mesh
    Plane084: THREE.Mesh
    Plane084_1: THREE.Mesh
    Plane111: THREE.Mesh
    Plane111_1: THREE.Mesh
    Plane112: THREE.Mesh
    Plane112_1: THREE.Mesh
    Plane113: THREE.Mesh
    Plane113_1: THREE.Mesh
    Plane114: THREE.Mesh
    Plane114_1: THREE.Mesh
    Plane115: THREE.Mesh
    Plane115_1: THREE.Mesh
    Plane116: THREE.Mesh
    Plane116_1: THREE.Mesh
    Plane117: THREE.Mesh
    Plane117_1: THREE.Mesh
    Plane118: THREE.Mesh
    Plane118_1: THREE.Mesh
    Plane129: THREE.Mesh
    Plane129_1: THREE.Mesh
    Plane130: THREE.Mesh
    Plane130_1: THREE.Mesh
    Plane132: THREE.Mesh
    Plane132_1: THREE.Mesh
    Plane142: THREE.Mesh
    Plane142_1: THREE.Mesh
    Plane145: THREE.Mesh
    Plane145_1: THREE.Mesh
    Plane152: THREE.Mesh
    Plane152_1: THREE.Mesh
    Plane153: THREE.Mesh
    Plane153_1: THREE.Mesh
    Plane154: THREE.Mesh
    Plane154_1: THREE.Mesh
    Plane155: THREE.Mesh
    Plane155_1: THREE.Mesh
    Plane156: THREE.Mesh
    Plane156_1: THREE.Mesh
    Plane157: THREE.Mesh
    Plane157_1: THREE.Mesh
    Plane158: THREE.Mesh
    Plane158_1: THREE.Mesh
    Plane159: THREE.Mesh
    Plane159_1: THREE.Mesh
    Plane160: THREE.Mesh
    Plane160_1: THREE.Mesh
    Plane164: THREE.Mesh
    Plane164_1: THREE.Mesh
    Plane165: THREE.Mesh
    Plane165_1: THREE.Mesh
    Plane166: THREE.Mesh
    Plane166_1: THREE.Mesh
    Plane167: THREE.Mesh
    Plane167_1: THREE.Mesh
    Plane168: THREE.Mesh
    Plane168_1: THREE.Mesh
    Plane169: THREE.Mesh
    Plane169_1: THREE.Mesh
    Plane171: THREE.Mesh
    Plane171_1: THREE.Mesh
    Plane172: THREE.Mesh
    Plane172_1: THREE.Mesh
    Plane173: THREE.Mesh
    Plane173_1: THREE.Mesh
    Plane174: THREE.Mesh
    Plane174_1: THREE.Mesh
    Plane175: THREE.Mesh
    Plane175_1: THREE.Mesh
    Plane176: THREE.Mesh
    Plane176_1: THREE.Mesh
    Plane177: THREE.Mesh
    Plane177_1: THREE.Mesh
    Plane180: THREE.Mesh
    Plane180_1: THREE.Mesh
    Plane181: THREE.Mesh
    Plane181_1: THREE.Mesh
    Plane182: THREE.Mesh
    Plane182_1: THREE.Mesh
    Plane183: THREE.Mesh
    Plane183_1: THREE.Mesh
    Plane184: THREE.Mesh
    Plane184_1: THREE.Mesh
    Plane185: THREE.Mesh
    Plane185_1: THREE.Mesh
    Plane186: THREE.Mesh
    Plane186_1: THREE.Mesh
    Plane187: THREE.Mesh
    Plane187_1: THREE.Mesh
    Plane188: THREE.Mesh
    Plane188_1: THREE.Mesh
    Plane189: THREE.Mesh
    Plane189_1: THREE.Mesh
    Plane190: THREE.Mesh
    Plane190_1: THREE.Mesh
    Plane191: THREE.Mesh
    Plane191_1: THREE.Mesh
    Plane192: THREE.Mesh
    Plane192_1: THREE.Mesh
    Plane193: THREE.Mesh
    Plane193_1: THREE.Mesh
    Plane194: THREE.Mesh
    Plane194_1: THREE.Mesh
    Plane195: THREE.Mesh
    Plane195_1: THREE.Mesh
    Plane196: THREE.Mesh
    Plane196_1: THREE.Mesh
    Plane197: THREE.Mesh
    Plane197_1: THREE.Mesh
    Plane198: THREE.Mesh
    Plane198_1: THREE.Mesh
    Plane199: THREE.Mesh
    Plane199_1: THREE.Mesh
    Plane200: THREE.Mesh
    Plane200_1: THREE.Mesh
    Plane201: THREE.Mesh
    Plane201_1: THREE.Mesh
    Plane202: THREE.Mesh
    Plane202_1: THREE.Mesh
    Plane203: THREE.Mesh
    Plane203_1: THREE.Mesh
    Plane204: THREE.Mesh
    Plane204_1: THREE.Mesh
    Plane205: THREE.Mesh
    Plane205_1: THREE.Mesh
    Plane206: THREE.Mesh
    Plane206_1: THREE.Mesh
    Plane207: THREE.Mesh
    Plane207_1: THREE.Mesh
    Plane208: THREE.Mesh
    Plane208_1: THREE.Mesh
    Plane209: THREE.Mesh
    Plane209_1: THREE.Mesh
    Plane210: THREE.Mesh
    Plane210_1: THREE.Mesh
    Plane211: THREE.Mesh
    Plane211_1: THREE.Mesh
    Plane212: THREE.Mesh
    Plane212_1: THREE.Mesh
    Plane213: THREE.Mesh
    Plane213_1: THREE.Mesh
    Plane214: THREE.Mesh
    Plane214_1: THREE.Mesh
    Plane215: THREE.Mesh
    Plane215_1: THREE.Mesh
    Plane216: THREE.Mesh
    Plane216_1: THREE.Mesh
    Plane217: THREE.Mesh
    Plane217_1: THREE.Mesh
    Plane218: THREE.Mesh
    Plane218_1: THREE.Mesh
    Plane219: THREE.Mesh
    Plane219_1: THREE.Mesh
    Plane220: THREE.Mesh
    Plane220_1: THREE.Mesh
    Plane221: THREE.Mesh
    Plane221_1: THREE.Mesh
    Plane222: THREE.Mesh
    Plane222_1: THREE.Mesh
    Plane223: THREE.Mesh
    Plane223_1: THREE.Mesh
    Plane224: THREE.Mesh
    Plane224_1: THREE.Mesh
    Plane225: THREE.Mesh
    Plane225_1: THREE.Mesh
    Plane226: THREE.Mesh
    Plane226_1: THREE.Mesh
    Plane227: THREE.Mesh
    Plane227_1: THREE.Mesh
    Plane228: THREE.Mesh
    Plane228_1: THREE.Mesh
    Plane229: THREE.Mesh
    Plane229_1: THREE.Mesh
    Plane230: THREE.Mesh
    Plane230_1: THREE.Mesh
    Plane231: THREE.Mesh
    Plane231_1: THREE.Mesh
    Plane232: THREE.Mesh
    Plane232_1: THREE.Mesh
    Plane233: THREE.Mesh
    Plane233_1: THREE.Mesh
    Plane234: THREE.Mesh
    Plane234_1: THREE.Mesh
    Plane235: THREE.Mesh
    Plane235_1: THREE.Mesh
    Plane236: THREE.Mesh
    Plane236_1: THREE.Mesh
    Plane237: THREE.Mesh
    Plane237_1: THREE.Mesh
    Plane239: THREE.Mesh
    Plane239_1: THREE.Mesh
    Plane240: THREE.Mesh
    Plane240_1: THREE.Mesh
    Plane244: THREE.Mesh
    Plane244_1: THREE.Mesh
    Plane245: THREE.Mesh
    Plane245_1: THREE.Mesh
    Plane246: THREE.Mesh
    Plane246_1: THREE.Mesh
    Plane247: THREE.Mesh
    Plane247_1: THREE.Mesh
    Plane248: THREE.Mesh
    Plane248_1: THREE.Mesh
    Plane249: THREE.Mesh
    Plane249_1: THREE.Mesh
    Plane250: THREE.Mesh
    Plane250_1: THREE.Mesh
    Plane251: THREE.Mesh
    Plane251_1: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'planeAction.002'
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d/world.gltf') as GLTFResult
  // const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={1.5}>
      <group name="Scene">
        <group name="ship2" position={[-0.12, 0.66, 0.74]} rotation={[1.78, 0.95, -0.5]} scale={1.47}>
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.006']} />
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['Material.007']} />
          <mesh name="Plane002_3" geometry={nodes.Plane002_3.geometry} material={materials['Material.008']} />
        </group>
        <group name="plane" rotation={[0, 0, 0.29]} scale={1.24}>
          <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['Material.009']} />
          <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials['Material.010']} />
        </group>
        <mesh name="clouds" geometry={nodes.clouds.geometry} material={materials['Material.005']} rotation={[-0.25, 0.05, 0.25]} />
        <group name="Icosphere001">
          <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials['Material.001']} />
          <mesh name="Icosphere003_1" geometry={nodes.Icosphere003_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="tree" position={[-0.52, 0.12, -0.89]} rotation={[-1.27, -0.38, 0.51]} scale={1.25}>
          <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials['Material.003']} />
          <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials['Material.004']} />
        </group>
        <group name="Plane" position={[-0.14, -0.39, -1.01]} rotation={[-1.81, -0.86, 0.22]} scale={1.92}>
          <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials['Material.013']} />
          <mesh name="Plane007_2" geometry={nodes.Plane007_2.geometry} material={materials['Material.014']} />
        </group>
        <group name="ship2001" position={[0.97, -0.06, 0.25]} rotation={[-0.98, 0.22, -2.03]} scale={1.47}>
          <mesh name="Plane008_1" geometry={nodes.Plane008_1.geometry} material={materials['Material.006']} />
          <mesh name="Plane008_2" geometry={nodes.Plane008_2.geometry} material={materials['Material.007']} />
          <mesh name="Plane008_3" geometry={nodes.Plane008_3.geometry} material={materials['Material.008']} />
        </group>
        <group name="ship2002" position={[-0.64, -0.76, -0.02]} rotation={[0.24, 0.05, 2.49]} scale={1.47}>
          <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['Material.006']} />
          <mesh name="Plane009_2" geometry={nodes.Plane009_2.geometry} material={materials['Material.007']} />
          <mesh name="Plane009_3" geometry={nodes.Plane009_3.geometry} material={materials['Material.008']} />
        </group>
        <group name="tree001" position={[-0.71, 0.11, -0.74]} rotation={[-1.16, -0.3, 0.83]} scale={1.25}>
          <mesh name="Plane014_1" geometry={nodes.Plane014_1.geometry} material={materials['Material.003']} />
          <mesh name="Plane014_2" geometry={nodes.Plane014_2.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree002" position={[-0.64, -0.03, -0.82]} rotation={[-1.27, -0.41, 0.87]} scale={1.25}>
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.003']} />
          <mesh name="Plane016_1" geometry={nodes.Plane016_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree003" position={[-0.96, -0.11, -0.39]} rotation={[-1.19, -0.29, 1.17]} scale={1.25}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.003']} />
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree004" position={[-0.88, -0.13, -0.53]} rotation={[-1.19, -0.29, 1.17]} scale={1.25}>
          <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials['Material.003']} />
          <mesh name="Plane038_1" geometry={nodes.Plane038_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree005" position={[-0.92, -0.29, -0.4]} rotation={[-1.23, -0.44, 1.42]} scale={1.25}>
          <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['Material.003']} />
          <mesh name="Plane039_1" geometry={nodes.Plane039_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree006" position={[-0.78, -0.14, -0.67]} rotation={[-1.23, -0.44, 0.89]} scale={1.25}>
          <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['Material.003']} />
          <mesh name="Plane040_1" geometry={nodes.Plane040_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree007" position={[-0.8, -0.34, -0.56]} rotation={[-1.33, -0.57, 1.11]} scale={1.25}>
          <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials['Material.003']} />
          <mesh name="Plane043_1" geometry={nodes.Plane043_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree008" position={[-0.46, -0.07, -0.92]} rotation={[-1.33, -0.57, 0.57]} scale={1.25}>
          <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials['Material.003']} />
          <mesh name="Plane047_1" geometry={nodes.Plane047_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree009" position={[-0.25, -0.1, -1.05]} rotation={[-1.53, -0.64, 0.2]} scale={1.25}>
          <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['Material.003']} />
          <mesh name="Plane049_1" geometry={nodes.Plane049_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree010" position={[-0.08, -0.21, -1.06]} rotation={[-1.74, -0.65, 0.01]} scale={1.25}>
          <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials['Material.003']} />
          <mesh name="Plane052_1" geometry={nodes.Plane052_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree011" position={[-0.66, 0.75, -0.27]} rotation={[-0.29, -0.12, 0.62]} scale={1.25}>
          <mesh name="Plane080" geometry={nodes.Plane080.geometry} material={materials['Material.003']} />
          <mesh name="Plane080_1" geometry={nodes.Plane080_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree012" position={[-0.81, 0.6, -0.24]} rotation={[-0.2, -0.03, 0.91]} scale={1.25}>
          <mesh name="Plane081" geometry={nodes.Plane081.geometry} material={materials['Material.003']} />
          <mesh name="Plane081_1" geometry={nodes.Plane081_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree013" position={[-0.73, 0.8, 0.02]} rotation={[-0.07, 0.1, 0.66]} scale={1.25}>
          <mesh name="Plane082" geometry={nodes.Plane082.geometry} material={materials['Material.003']} />
          <mesh name="Plane082_1" geometry={nodes.Plane082_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree014" position={[-0.86, 0.65, -0.02]} rotation={[-0.09, 0.08, 0.84]} scale={1.25}>
          <mesh name="Plane084" geometry={nodes.Plane084.geometry} material={materials['Material.003']} />
          <mesh name="Plane084_1" geometry={nodes.Plane084_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree015" position={[-0.79, 0.73, 0.17]} rotation={[0, 0.19, 0.93]} scale={1.25}>
          <mesh name="Plane111" geometry={nodes.Plane111.geometry} material={materials['Material.003']} />
          <mesh name="Plane111_1" geometry={nodes.Plane111_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree016" position={[-0.93, 0.45, -0.05]} rotation={[-0.09, 0.04, 1.2]} scale={1.25}>
          <mesh name="Plane112" geometry={nodes.Plane112.geometry} material={materials['Material.003']} />
          <mesh name="Plane112_1" geometry={nodes.Plane112_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree017" position={[-0.92, 0.45, 0.15]} rotation={[-0.03, 0.18, 1.12]} scale={1.25}>
          <mesh name="Plane113" geometry={nodes.Plane113.geometry} material={materials['Material.003']} />
          <mesh name="Plane113_1" geometry={nodes.Plane113_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree018" position={[-0.88, 0.45, 0.34]} rotation={[0.04, 0.32, 1.2]} scale={1.25}>
          <mesh name="Plane114" geometry={nodes.Plane114.geometry} material={materials['Material.003']} />
          <mesh name="Plane114_1" geometry={nodes.Plane114_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree019" position={[-0.82, 0.62, 0.36]} rotation={[0.06, 0.36, 0.86]} scale={1.25}>
          <mesh name="Plane115" geometry={nodes.Plane115.geometry} material={materials['Material.003']} />
          <mesh name="Plane115_1" geometry={nodes.Plane115_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree020" position={[-0.65, 0.58, 0.57]} rotation={[0.27, 0.56, 0.82]} scale={1.25}>
          <mesh name="Plane116" geometry={nodes.Plane116.geometry} material={materials['Material.003']} />
          <mesh name="Plane116_1" geometry={nodes.Plane116_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree021" position={[-0.65, 0.67, 0.48]} rotation={[0.27, 0.56, 0.82]} scale={1.25}>
          <mesh name="Plane117" geometry={nodes.Plane117.geometry} material={materials['Material.003']} />
          <mesh name="Plane117_1" geometry={nodes.Plane117_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree022" position={[-0.73, 0.72, 0.34]} rotation={[0.06, 0.36, 0.86]} scale={1.25}>
          <mesh name="Plane118" geometry={nodes.Plane118.geometry} material={materials['Material.003']} />
          <mesh name="Plane118_1" geometry={nodes.Plane118_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree023" position={[-0.49, 0.72, 0.57]} rotation={[0.33, 0.58, 0.66]} scale={1.25}>
          <mesh name="Plane129" geometry={nodes.Plane129.geometry} material={materials['Material.003']} />
          <mesh name="Plane129_1" geometry={nodes.Plane129_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree024" position={[-0.37, 0.8, 0.55]} rotation={[0.28, 0.56, 0.38]} scale={1.25}>
          <mesh name="Plane130" geometry={nodes.Plane130.geometry} material={materials['Material.003']} />
          <mesh name="Plane130_1" geometry={nodes.Plane130_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree025" position={[-0.3, 0.9, 0.42]} rotation={[0.28, 0.56, 0.38]} scale={1.25}>
          <mesh name="Plane132" geometry={nodes.Plane132.geometry} material={materials['Material.003']} />
          <mesh name="Plane132_1" geometry={nodes.Plane132_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree026" position={[-0.31, 0.95, 0.27]} rotation={[0.16, 0.52, 0.31]} scale={1.25}>
          <mesh name="Plane142" geometry={nodes.Plane142.geometry} material={materials['Material.003']} />
          <mesh name="Plane142_1" geometry={nodes.Plane142_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree027" position={[-0.48, 0.85, 0.38]} rotation={[0.21, 0.54, 0.58]} scale={1.25}>
          <mesh name="Plane145" geometry={nodes.Plane145.geometry} material={materials['Material.003']} />
          <mesh name="Plane145_1" geometry={nodes.Plane145_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree028" position={[-0.43, 0.93, 0.16]} rotation={[-0.02, 0.43, 0.43]} scale={1.25}>
          <mesh name="Plane152" geometry={nodes.Plane152.geometry} material={materials['Material.003']} />
          <mesh name="Plane152_1" geometry={nodes.Plane152_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree029" position={[-0.64, -0.11, 0.81]} rotation={[0.49, 0.94, 1.35]} scale={1.25}>
          <mesh name="Plane153" geometry={nodes.Plane153.geometry} material={materials['Material.003']} />
          <mesh name="Plane153_1" geometry={nodes.Plane153_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree030" position={[-0.59, -0.23, 0.82]} rotation={[0.49, 0.94, 1.35]} scale={1.25}>
          <mesh name="Plane154" geometry={nodes.Plane154.geometry} material={materials['Material.003']} />
          <mesh name="Plane154_1" geometry={nodes.Plane154_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree031" position={[-0.74, -0.15, 0.71]} rotation={[0.44, 0.77, 1.36]} scale={1.25}>
          <mesh name="Plane155" geometry={nodes.Plane155.geometry} material={materials['Material.003']} />
          <mesh name="Plane155_1" geometry={nodes.Plane155_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree032" position={[-0.69, -0.34, 0.7]} rotation={[0.45, 0.89, 1.69]} scale={1.25}>
          <mesh name="Plane156" geometry={nodes.Plane156.geometry} material={materials['Material.003']} />
          <mesh name="Plane156_1" geometry={nodes.Plane156_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree033" position={[-0.81, -0.27, 0.59]} rotation={[0.45, 0.65, 1.49]} scale={1.25}>
          <mesh name="Plane157" geometry={nodes.Plane157.geometry} material={materials['Material.003']} />
          <mesh name="Plane157_1" geometry={nodes.Plane157_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree034" position={[-0.7, -0.47, 0.6]} rotation={[0.45, 0.89, 1.69]} scale={1.25}>
          <mesh name="Plane158" geometry={nodes.Plane158.geometry} material={materials['Material.003']} />
          <mesh name="Plane158_1" geometry={nodes.Plane158_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree035" position={[-0.5, -0.34, 0.85]} rotation={[0.43, 1, 1.56]} scale={1.25}>
          <mesh name="Plane159" geometry={nodes.Plane159.geometry} material={materials['Material.003']} />
          <mesh name="Plane159_1" geometry={nodes.Plane159_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree036" position={[-0.54, -0.45, 0.77]} rotation={[0.43, 1, 1.56]} scale={1.25}>
          <mesh name="Plane160" geometry={nodes.Plane160.geometry} material={materials['Material.003']} />
          <mesh name="Plane160_1" geometry={nodes.Plane160_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree040" position={[-0.56, -0.64, 0.67]} rotation={[0.6, 0.98, 1.74]} scale={1.25}>
          <mesh name="Plane164" geometry={nodes.Plane164.geometry} material={materials['Material.003']} />
          <mesh name="Plane164_1" geometry={nodes.Plane164_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree041" position={[-0.39, -0.75, 0.68]} rotation={[0.53, 1.15, 1.79]} scale={1.25}>
          <mesh name="Plane165" geometry={nodes.Plane165.geometry} material={materials['Material.003']} />
          <mesh name="Plane165_1" geometry={nodes.Plane165_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree042" position={[-0.49, -0.8, 0.57]} rotation={[0.64, 1, 2.01]} scale={1.25}>
          <mesh name="Plane166" geometry={nodes.Plane166.geometry} material={materials['Material.003']} />
          <mesh name="Plane166_1" geometry={nodes.Plane166_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree043" position={[-0.63, -0.72, 0.5]} rotation={[0.69, 0.91, 1.81]} scale={1.25}>
          <mesh name="Plane167" geometry={nodes.Plane167.geometry} material={materials['Material.003']} />
          <mesh name="Plane167_1" geometry={nodes.Plane167_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree044" position={[-0.56, -0.84, 0.37]} rotation={[0.64, 1, 2.01]} scale={1.25}>
          <mesh name="Plane168" geometry={nodes.Plane168.geometry} material={materials['Material.003']} />
          <mesh name="Plane168_1" geometry={nodes.Plane168_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree045" position={[-0.38, -0.91, 0.45]} rotation={[0.46, 1.15, 2.16]} scale={1.25}>
          <mesh name="Plane169" geometry={nodes.Plane169.geometry} material={materials['Material.003']} />
          <mesh name="Plane169_1" geometry={nodes.Plane169_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree046" position={[-0.33, -0.85, 0.59]} rotation={[0.34, 1.22, 2.12]} scale={1.25}>
          <mesh name="Plane171" geometry={nodes.Plane171.geometry} material={materials['Material.003']} />
          <mesh name="Plane171_1" geometry={nodes.Plane171_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree047" position={[-0.27, -0.15, 1.04]} rotation={[0.32, 1.26, 1.44]} scale={1.25}>
          <mesh name="Plane172" geometry={nodes.Plane172.geometry} material={materials['Material.003']} />
          <mesh name="Plane172_1" geometry={nodes.Plane172_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree048" position={[-0.13, 0.1, 1.07]} rotation={[0.5, 1.38, 0.99]} scale={1.25}>
          <mesh name="Plane173" geometry={nodes.Plane173.geometry} material={materials['Material.003']} />
          <mesh name="Plane173_1" geometry={nodes.Plane173_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree049" position={[-0.28, 0.03, 1.05]} rotation={[0.5, 1.38, 0.99]} scale={1.25}>
          <mesh name="Plane174" geometry={nodes.Plane174.geometry} material={materials['Material.003']} />
          <mesh name="Plane174_1" geometry={nodes.Plane174_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree050" position={[-0.36, 0.17, 1.01]} rotation={[0.21, 1.24, 1.18]} scale={1.25}>
          <mesh name="Plane175" geometry={nodes.Plane175.geometry} material={materials['Material.003']} />
          <mesh name="Plane175_1" geometry={nodes.Plane175_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree051" position={[-0.46, 0.09, 0.97]} rotation={[0.11, 1.09, 1.38]} scale={1.25}>
          <mesh name="Plane176" geometry={nodes.Plane176.geometry} material={materials['Material.003']} />
          <mesh name="Plane176_1" geometry={nodes.Plane176_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree052" position={[-0.51, -0.09, 0.95]} rotation={[0.11, 1.11, 1.55]} scale={1.25}>
          <mesh name="Plane177" geometry={nodes.Plane177.geometry} material={materials['Material.003']} />
          <mesh name="Plane177_1" geometry={nodes.Plane177_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree053" position={[-0.4, -0.06, 1.01]} rotation={[0.11, 1.11, 1.55]} scale={1.25}>
          <mesh name="Plane180" geometry={nodes.Plane180.geometry} material={materials['Material.003']} />
          <mesh name="Plane180_1" geometry={nodes.Plane180_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree054" position={[0.3, -1, -0.3]} rotation={[-0.49, 1.2, -2.3]} scale={1.25}>
          <mesh name="Plane181" geometry={nodes.Plane181.geometry} material={materials['Material.003']} />
          <mesh name="Plane181_1" geometry={nodes.Plane181_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree055" position={[0.41, -0.99, -0.15]} rotation={[-0.71, 1.09, -2.2]} scale={1.25}>
          <mesh name="Plane182" geometry={nodes.Plane182.geometry} material={materials['Material.003']} />
          <mesh name="Plane182_1" geometry={nodes.Plane182_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree056" position={[0.51, -0.89, 0.12]} rotation={[-1, 0.87, -2.19]} scale={1.25}>
          <mesh name="Plane183" geometry={nodes.Plane183.geometry} material={materials['Material.003']} />
          <mesh name="Plane183_1" geometry={nodes.Plane183_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree057" position={[0.59, -0.85, -0.05]} rotation={[-1.02, 0.84, -2]} scale={1.25}>
          <mesh name="Plane184" geometry={nodes.Plane184.geometry} material={materials['Material.003']} />
          <mesh name="Plane184_1" geometry={nodes.Plane184_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree058" position={[0.64, -0.75, 0.33]} rotation={[-1.09, 0.75, -2.24]} scale={1.25}>
          <mesh name="Plane185" geometry={nodes.Plane185.geometry} material={materials['Material.003']} />
          <mesh name="Plane185_1" geometry={nodes.Plane185_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree059" position={[0.71, -0.76, 0.15]} rotation={[-1.14, 0.69, -1.86]} scale={1.25}>
          <mesh name="Plane186" geometry={nodes.Plane186.geometry} material={materials['Material.003']} />
          <mesh name="Plane186_1" geometry={nodes.Plane186_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree060" position={[0.75, -0.71, -0.01]} rotation={[-1.14, 0.69, -1.86]} scale={1.25}>
          <mesh name="Plane187" geometry={nodes.Plane187.geometry} material={materials['Material.003']} />
          <mesh name="Plane187_1" geometry={nodes.Plane187_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree061" position={[0.86, -0.63, -0.18]} rotation={[-1.15, 0.66, -1.68]} scale={1.25}>
          <mesh name="Plane188" geometry={nodes.Plane188.geometry} material={materials['Material.003']} />
          <mesh name="Plane188_1" geometry={nodes.Plane188_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree062" position={[0.68, -0.86, -0.29]} rotation={[-1.11, 0.96, -1.64]} scale={1.25}>
          <mesh name="Plane189" geometry={nodes.Plane189.geometry} material={materials['Material.003']} />
          <mesh name="Plane189_1" geometry={nodes.Plane189_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree063" position={[0.48, -0.87, -0.43]} rotation={[-1.11, 1.08, -1.51]} scale={1.25}>
          <mesh name="Plane190" geometry={nodes.Plane190.geometry} material={materials['Material.003']} />
          <mesh name="Plane190_1" geometry={nodes.Plane190_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree064" position={[0.82, -0.68, -0.4]} rotation={[-1.1, 0.78, -1.59]} scale={1.25}>
          <mesh name="Plane191" geometry={nodes.Plane191.geometry} material={materials['Material.003']} />
          <mesh name="Plane191_1" geometry={nodes.Plane191_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree065" position={[0.94, -0.44, -0.33]} rotation={[-1.08, 0.48, -1.47]} scale={1.25}>
          <mesh name="Plane192" geometry={nodes.Plane192.geometry} material={materials['Material.003']} />
          <mesh name="Plane192_1" geometry={nodes.Plane192_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree066" position={[0.28, 0.39, 0.98]} rotation={[-1.68, -0.59, -2.77]} scale={1.25}>
          <mesh name="Plane193" geometry={nodes.Plane193.geometry} material={materials['Material.003']} />
          <mesh name="Plane193_1" geometry={nodes.Plane193_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree067" position={[0.21, 0.55, 0.91]} rotation={[-2.03, -0.67, -2.92]} scale={1.25}>
          <mesh name="Plane194" geometry={nodes.Plane194.geometry} material={materials['Material.003']} />
          <mesh name="Plane194_1" geometry={nodes.Plane194_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree068" position={[0.45, 0.42, 0.93]} rotation={[-1.76, -0.57, -2.5]} scale={1.25}>
          <mesh name="Plane195" geometry={nodes.Plane195.geometry} material={materials['Material.003']} />
          <mesh name="Plane195_1" geometry={nodes.Plane195_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree069" position={[0.35, 0.58, 0.89]} rotation={[-1.84, -0.62, -2.53]} scale={1.25}>
          <mesh name="Plane196" geometry={nodes.Plane196.geometry} material={materials['Material.003']} />
          <mesh name="Plane196_1" geometry={nodes.Plane196_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree070" position={[0.61, 0.2, 0.82]} rotation={[-1.5, -0.39, -2.47]} scale={1.25}>
          <mesh name="Plane197" geometry={nodes.Plane197.geometry} material={materials['Material.003']} />
          <mesh name="Plane197_1" geometry={nodes.Plane197_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree071" position={[0.73, 0.14, 0.72]} rotation={[-1.4, -0.3, -2.31]} scale={1.25}>
          <mesh name="Plane198" geometry={nodes.Plane198.geometry} material={materials['Material.003']} />
          <mesh name="Plane198_1" geometry={nodes.Plane198_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree072" position={[0.66, 0.4, 0.8]} rotation={[-1.77, -0.62, -2.47]} scale={1.25}>
          <mesh name="Plane199" geometry={nodes.Plane199.geometry} material={materials['Material.003']} />
          <mesh name="Plane199_1" geometry={nodes.Plane199_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree073" position={[0.51, 0.54, 0.8]} rotation={[-1.77, -0.62, -2.47]} scale={1.25}>
          <mesh name="Plane200" geometry={nodes.Plane200.geometry} material={materials['Material.003']} />
          <mesh name="Plane200_1" geometry={nodes.Plane200_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree074" position={[0.4, 0.7, 0.76]} rotation={[-1.81, -0.64, -2.52]} scale={1.25}>
          <mesh name="Plane201" geometry={nodes.Plane201.geometry} material={materials['Material.003']} />
          <mesh name="Plane201_1" geometry={nodes.Plane201_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree075" position={[0.36, 0.77, 0.61]} rotation={[-2.17, -0.8, -2.71]} scale={1.25}>
          <mesh name="Plane202" geometry={nodes.Plane202.geometry} material={materials['Material.003']} />
          <mesh name="Plane202_1" geometry={nodes.Plane202_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree076" position={[0.65, 0.61, 0.66]} rotation={[-1.77, -0.62, -2.5]} scale={1.25}>
          <mesh name="Plane203" geometry={nodes.Plane203.geometry} material={materials['Material.003']} />
          <mesh name="Plane203_1" geometry={nodes.Plane203_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree077" position={[0.52, 0.76, 0.63]} rotation={[-1.77, -0.62, -2.47]} scale={1.25}>
          <mesh name="Plane204" geometry={nodes.Plane204.geometry} material={materials['Material.003']} />
          <mesh name="Plane204_1" geometry={nodes.Plane204_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree078" position={[0.46, 0.85, 0.38]} rotation={[-2.06, -0.82, -2.33]} scale={1.25}>
          <mesh name="Plane205" geometry={nodes.Plane205.geometry} material={materials['Material.003']} />
          <mesh name="Plane205_1" geometry={nodes.Plane205_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree079" position={[0.63, 0.71, 0.41]} rotation={[-1.9, -0.69, -2.25]} scale={1.25}>
          <mesh name="Plane206" geometry={nodes.Plane206.geometry} material={materials['Material.003']} />
          <mesh name="Plane206_1" geometry={nodes.Plane206_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree080" position={[0.77, 0.51, 0.49]} rotation={[-1.71, -0.44, -2.05]} scale={1.25}>
          <mesh name="Plane207" geometry={nodes.Plane207.geometry} material={materials['Material.003']} />
          <mesh name="Plane207_1" geometry={nodes.Plane207_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree081" position={[0.76, 0.34, 0.62]} rotation={[-1.68, -0.38, -2.2]} scale={1.25}>
          <mesh name="Plane208" geometry={nodes.Plane208.geometry} material={materials['Material.003']} />
          <mesh name="Plane208_1" geometry={nodes.Plane208_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree082" position={[0.87, 0.45, 0.36]} rotation={[-1.71, -0.44, -2.05]} scale={1.25}>
          <mesh name="Plane209" geometry={nodes.Plane209.geometry} material={materials['Material.003']} />
          <mesh name="Plane209_1" geometry={nodes.Plane209_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree083" position={[0.91, 0.47, 0.19]} rotation={[-1.7, -0.4, -1.77]} scale={1.25}>
          <mesh name="Plane210" geometry={nodes.Plane210.geometry} material={materials['Material.003']} />
          <mesh name="Plane210_1" geometry={nodes.Plane210_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree084" position={[0.77, 0.63, 0.31]} rotation={[-1.78, -0.61, -2.05]} scale={1.25}>
          <mesh name="Plane211" geometry={nodes.Plane211.geometry} material={materials['Material.003']} />
          <mesh name="Plane211_1" geometry={nodes.Plane211_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree085" position={[0.82, 0.62, 0.14]} rotation={[-1.81, -0.66, -1.89]} scale={1.25}>
          <mesh name="Plane212" geometry={nodes.Plane212.geometry} material={materials['Material.003']} />
          <mesh name="Plane212_1" geometry={nodes.Plane212_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree086" position={[0.68, 0.82, 0.24]} rotation={[-2, -0.95, -2.13]} scale={1.25}>
          <mesh name="Plane213" geometry={nodes.Plane213.geometry} material={materials['Material.003']} />
          <mesh name="Plane213_1" geometry={nodes.Plane213_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree087" position={[0.72, 0.81, 0.07]} rotation={[-1.91, -0.82, -1.92]} scale={1.25}>
          <mesh name="Plane214" geometry={nodes.Plane214.geometry} material={materials['Material.003']} />
          <mesh name="Plane214_1" geometry={nodes.Plane214_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree088" position={[0.54, 0.92, 0.18]} rotation={[-2, -0.95, -2.13]} scale={1.25}>
          <mesh name="Plane215" geometry={nodes.Plane215.geometry} material={materials['Material.003']} />
          <mesh name="Plane215_1" geometry={nodes.Plane215_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree089" position={[0.13, 0.77, -0.68]} rotation={[-2.73, -1.45, -2.03]} scale={1.25}>
          <mesh name="Plane216" geometry={nodes.Plane216.geometry} material={materials['Material.003']} />
          <mesh name="Plane216_1" geometry={nodes.Plane216_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree090" position={[0.05, 0.63, -0.83]} rotation={[-2.96, -1.49, -2.08]} scale={1.25}>
          <mesh name="Plane217" geometry={nodes.Plane217.geometry} material={materials['Material.003']} />
          <mesh name="Plane217_1" geometry={nodes.Plane217_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree091" position={[-0.06, 0.77, -0.71]} rotation={[0.92, -1.38, 1.55]} scale={1.25}>
          <mesh name="Plane218" geometry={nodes.Plane218.geometry} material={materials['Material.003']} />
          <mesh name="Plane218_1" geometry={nodes.Plane218_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree092" position={[-0.24, 0.72, -0.71]} rotation={[0.85, -1.34, 1.65]} scale={1.25}>
          <mesh name="Plane219" geometry={nodes.Plane219.geometry} material={materials['Material.003']} />
          <mesh name="Plane219_1" geometry={nodes.Plane219_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree093" position={[-0.18, 0.62, -0.82]} rotation={[0.77, -1.47, 1.69]} scale={1.25}>
          <mesh name="Plane220" geometry={nodes.Plane220.geometry} material={materials['Material.003']} />
          <mesh name="Plane220_1" geometry={nodes.Plane220_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree094" position={[-0.17, 0.85, -0.57]} rotation={[0.92, -1.38, 1.55]} scale={1.25}>
          <mesh name="Plane221" geometry={nodes.Plane221.geometry} material={materials['Material.003']} />
          <mesh name="Plane221_1" geometry={nodes.Plane221_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree095" position={[0.07, 0.85, -0.59]} rotation={[0.53, -1.55, 1.11]} scale={1.25}>
          <mesh name="Plane222" geometry={nodes.Plane222.geometry} material={materials['Material.003']} />
          <mesh name="Plane222_1" geometry={nodes.Plane222_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree096" position={[0.6, 0.3, -0.86]} rotation={[-2.62, -0.99, -1.49]} scale={1.25}>
          <mesh name="Plane223" geometry={nodes.Plane223.geometry} material={materials['Material.003']} />
          <mesh name="Plane223_1" geometry={nodes.Plane223_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree097" position={[0.63, 0.43, -0.78]} rotation={[-2.62, -0.99, -1.49]} scale={1.25}>
          <mesh name="Plane224" geometry={nodes.Plane224.geometry} material={materials['Material.003']} />
          <mesh name="Plane224_1" geometry={nodes.Plane224_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree098" position={[0.85, 0.18, -0.65]} rotation={[-2.67, -0.65, -1.47]} scale={1.25}>
          <mesh name="Plane225" geometry={nodes.Plane225.geometry} material={materials['Material.003']} />
          <mesh name="Plane225_1" geometry={nodes.Plane225_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree099" position={[0.75, 0.14, -0.77]} rotation={[-2.64, -0.76, -1.32]} scale={1.25}>
          <mesh name="Plane226" geometry={nodes.Plane226.geometry} material={materials['Material.003']} />
          <mesh name="Plane226_1" geometry={nodes.Plane226_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree100" position={[0.75, 0.3, -0.74]} rotation={[-2.67, -0.65, -1.47]} scale={1.25}>
          <mesh name="Plane227" geometry={nodes.Plane227.geometry} material={materials['Material.003']} />
          <mesh name="Plane227_1" geometry={nodes.Plane227_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree101" position={[0.85, 0.33, -0.59]} rotation={[-2.67, -0.72, -1.64]} scale={1.25}>
          <mesh name="Plane228" geometry={nodes.Plane228.geometry} material={materials['Material.003']} />
          <mesh name="Plane228_1" geometry={nodes.Plane228_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree102" position={[0.75, 0.44, -0.65]} rotation={[-2.67, -0.72, -1.64]} scale={1.25}>
          <mesh name="Plane229" geometry={nodes.Plane229.geometry} material={materials['Material.003']} />
          <mesh name="Plane229_1" geometry={nodes.Plane229_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Plane001" position={[-0.32, -0.26, -1]} rotation={[-1.44, -0.77, 0.44]} scale={1.92}>
          <mesh name="Plane230" geometry={nodes.Plane230.geometry} material={materials['Material.013']} />
          <mesh name="Plane230_1" geometry={nodes.Plane230_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane002" position={[-0.42, -0.61, -0.83]} rotation={[-2.05, -0.18, 0.58]} scale={1.92}>
          <mesh name="Plane231" geometry={nodes.Plane231.geometry} material={materials['Material.013']} />
          <mesh name="Plane231_1" geometry={nodes.Plane231_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane003" position={[-0.6, -0.61, -0.7]} rotation={[-2.18, -0.27, 0.61]} scale={1.92}>
          <mesh name="Plane232" geometry={nodes.Plane232.geometry} material={materials['Material.013']} />
          <mesh name="Plane232_1" geometry={nodes.Plane232_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane004" position={[-0.58, -0.41, -0.85]} rotation={[-1.93, -0.1, 0.57]} scale={1.92}>
          <mesh name="Plane233" geometry={nodes.Plane233.geometry} material={materials['Material.013']} />
          <mesh name="Plane233_1" geometry={nodes.Plane233_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane005" position={[-0.6, -0.16, -0.83]} rotation={[0.17, -1, 2.22]} scale={1.92}>
          <mesh name="Plane234" geometry={nodes.Plane234.geometry} material={materials['Material.013']} />
          <mesh name="Plane234_1" geometry={nodes.Plane234_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="tree103" position={[-0.71, -0.46, -0.72]} rotation={[-1.42, -0.7, 0.96]} scale={1.25}>
          <mesh name="Plane235" geometry={nodes.Plane235.geometry} material={materials['Material.003']} />
          <mesh name="Plane235_1" geometry={nodes.Plane235_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree104" position={[-0.82, -0.44, -0.44]} rotation={[-1.35, -0.57, 1.27]} scale={1.25}>
          <mesh name="Plane236" geometry={nodes.Plane236.geometry} material={materials['Material.003']} />
          <mesh name="Plane236_1" geometry={nodes.Plane236_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Plane006" position={[0.85, -0.53, -0.43]} rotation={[-3.04, -0.45, -0.93]} scale={1.92}>
          <mesh name="Plane237" geometry={nodes.Plane237.geometry} material={materials['Material.013']} />
          <mesh name="Plane237_1" geometry={nodes.Plane237_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane008" position={[0.29, -0.96, 0.26]} rotation={[2.94, 0.39, -0.29]} scale={1.92}>
          <mesh name="Plane239" geometry={nodes.Plane239.geometry} material={materials['Material.013']} />
          <mesh name="Plane239_1" geometry={nodes.Plane239_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane009" position={[0.09, -1.03, 0.09]} rotation={[3.03, 0.29, -0.07]} scale={1.92}>
          <mesh name="Plane240" geometry={nodes.Plane240.geometry} material={materials['Material.013']} />
          <mesh name="Plane240_1" geometry={nodes.Plane240_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="tree105" position={[0.33, -0.98, 0]} rotation={[-0.62, 1.09, -2.46]} scale={1.25}>
          <mesh name="Plane244" geometry={nodes.Plane244.geometry} material={materials['Material.003']} />
          <mesh name="Plane244_1" geometry={nodes.Plane244_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="tree106" position={[0.39, -0.95, 0.14]} rotation={[-0.83, 1, -2.39]} scale={1.25}>
          <mesh name="Plane245" geometry={nodes.Plane245.geometry} material={materials['Material.003']} />
          <mesh name="Plane245_1" geometry={nodes.Plane245_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Plane007" position={[0.63, 0.88, -0.1]} rotation={[-2.92, -0.38, -2.38]} scale={1.92}>
          <mesh name="Plane246" geometry={nodes.Plane246.geometry} material={materials['Material.013']} />
          <mesh name="Plane246_1" geometry={nodes.Plane246_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane010" position={[0.5, 0.97, -0.04]} rotation={[-3.02, -0.46, -2.71]} scale={1.92}>
          <mesh name="Plane247" geometry={nodes.Plane247.geometry} material={materials['Material.013']} />
          <mesh name="Plane247_1" geometry={nodes.Plane247_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane011" position={[0.38, 1.01, 0.08]} rotation={[-2.86, -0.39, -2.72]} scale={1.92}>
          <mesh name="Plane248" geometry={nodes.Plane248.geometry} material={materials['Material.013']} />
          <mesh name="Plane248_1" geometry={nodes.Plane248_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane012" position={[-0.2, -0.39, 0.94]} rotation={[-1.21, -0.33, 2.99]} scale={1.92}>
          <mesh name="Plane249" geometry={nodes.Plane249.geometry} material={materials['Material.013']} />
          <mesh name="Plane249_1" geometry={nodes.Plane249_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane013" position={[-0.37, -0.4, 0.88]} rotation={[-1.27, -0.31, 2.68]} scale={1.92}>
          <mesh name="Plane250" geometry={nodes.Plane250.geometry} material={materials['Material.013']} />
          <mesh name="Plane250_1" geometry={nodes.Plane250_1.geometry} material={materials['Material.014']} />
        </group>
        <group name="Plane014" position={[-0.3, -0.58, 0.81]} rotation={[-0.16, 1.36, 1.98]} scale={1.92}>
          <mesh name="Plane251" geometry={nodes.Plane251.geometry} material={materials['Material.013']} />
          <mesh name="Plane251_1" geometry={nodes.Plane251_1.geometry} material={materials['Material.014']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/world.gltf')
